# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks:
  armut:
    driver: bridge

services:
  api:
    image: api
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 7060:7060
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image; Database=messaging; Username=burakakkaya; Password=burakakkaya"
    networks:
      - armut

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "burakakkaya"
      POSTGRES_PASSWORD: "burakakkaya"
      POSTGRES_DB: "messaging"
    networks:
      - armut
  
volumes:
  db_volume:
